name: Bump version

on:
  push:
    branches: 
    - main
jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@main
      with:
        API_KEY: ${{ secrets.API_KEY }}
        tag-prefix:  'v'
